services:
    test_app:
      network_mode: “host”
    postgres:
        image: postgres
        environment:
          - POSTGRES_DB=postgres
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_HOST_AUTH_METHOD: trust
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5433:5433'
        volumes: 
          - ./postgres-data:/var/lib/postgresql/data
          - ./db/shema.sql:/docker-entrypoint-initdb.d/create_tables.sqlx