CREATE TABLE SEGMENTS (
    ID SERIAL PRIMARY KEY,
    SEGMENT_NAME VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE USER_SEGMENTS (
    ID SERIAL PRIMARY KEY,
    USER_ID INT,
    SEGMENT_NAMES VARCHAR[],
    EXPIRE_DATE TIMESTAMP
);

CREATE INDEX idx_user_id ON USER_SEGMENTS(USER_ID);

CREATE FUNCTION remove_old_rows() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  DELETE FROM USER_SEGMENTS WHERE EXPIRE_DATE < NOW();
  RETURN NEW;
END;
$$;

CREATE TRIGGER remove_old_rows_trigger
    AFTER INSERT ON USER_SEGMENTS
EXECUTE PROCEDURE remove_old_rows();

CREATE TABLE HISTORY (
    ID SERIAL PRIMARY KEY,
    USER_ID INT,
    OPERATION_TYPE VARCHAR(255),
    SEGMENT_NAME VARCHAR(255),
    OP_DATE DATE
);

