CREATE TABLE SEGMENTS (
    ID SERIAL PRIMARY KEY,
    SEGMENT_NAME VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE SEGMENTS_USERS (
    SEGMENT_ID INT REFERENCES segments(ID) ON DELETE CASCADE,
    USER_ID INT REFERENCES users(ID) ON DELETE CASCADE 
);

CREATE TABLE USERS(
    ID SERIAL PRIMARY KEY,
    EXPIRE_DATE DATE
);

CREATE FUNCTION remove_old_users() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  DELETE FROM USER_SEGMENTS WHERE EXPIRE_DATE < NOW();
  RETURN NEW;
END;
$$;

CREATE TRIGGER remove_old_rows_trigger
    AFTER INSERT ON USER_SEGMENTS
EXECUTE PROCEDURE remove_old_rows();

CREATE TABLE HISTORY (
    ID SERIAL PRIMARY KEY,
    USER_ID INT,
    OPERATION_TYPE VARCHAR(255),
    SEGMENT_NAME VARCHAR(255),
    OP_DATE DATE
);

